# Generated by Django 3.1.7 on 2022-11-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('age', models.IntegerField(default=0)),
                ('salary', models.CharField(max_length=1000, null=True)),
                ('code', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
